### ISSUE TITLE
Hands and fingers are not shown in 3D Model

### ISSUE THREAD

**Issue by rem0g** [vladmandic/holistic#1]
I have downloaded the repo via github clone and ran it with npm start, when testing videos I noticed there are no hands and fingers shown in 3D Model. Hoewer they are drawn on the 2D video and in your screenshot all of those are visible. 

Settings are the same as the ones in your screenshot.  At your live link i am getting same results with no hands/fingers.

Is this a bug or do i need to make adjustments to the code? I also have update mediapipe Holistic version. 

Thank you

**Comment by vladmandic** [comment]
hmm, you're right, they seem to have dissapeared - but they were there, you can clearly see in a screenshot in readme. i'll take a look at what happened.

**Comment by vladmandic** [comment]
fixed.
